[theme]
base = "dark"
backgroundColor = "#191b37"
secondaryBackgroundColor = "#272945"
textColor = "#ffffff"

[global]
dataFrameSerialization = "arrow"

enableCORS = false

enableXsrfProtection = false

enableWebsocketCompression = false
